# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckeditor_filer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailoption',
            name='height',
            field=models.IntegerField(blank=True, default=0, help_text='height in pixel.', verbose_name='height'),
        ),
    ]
